CREATE TABLE IF NOT EXISTS public.contratos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL,
    titulo VARCHAR(255) NOT NULL,
    valor DECIMAL(10,2) NOT NULL DEFAULT 0,
    dia_vencimento INTEGER NOT NULL, -- Ex: 5, 10, 15
    ciclo VARCHAR(20) DEFAULT 'mensal', -- 'mensal', 'trimestral', 'semestral', 'anual'
    status VARCHAR(20) DEFAULT 'ativo', -- 'ativo', 'suspenso', 'cancelado'
    data_inicio DATE DEFAULT CURRENT_DATE,
    proxima_cobranca DATE, -- Usado para controlar quando gerar a próxima fatura
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_contratos_user_id ON public.contratos(user_id);
CREATE INDEX IF NOT EXISTS idx_contratos_status ON public.contratos(status);
CREATE INDEX IF NOT EXISTS idx_contratos_cliente_id ON public.contratos(cliente_id);

-- RLS Policies (Segurança)
ALTER TABLE public.contratos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own contracts"
    ON public.contratos FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own contracts"
    ON public.contratos FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own contracts"
    ON public.contratos FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own contracts"
    ON public.contratos FOR DELETE
    USING (auth.uid() = user_id);
